steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rick-devops-01/mytest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rick-devops-01/mytest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cr-example', '--image', 'gcr.io/rick-devops-01/mytest', '--region', 'us-east1']
images:
- gcr.io/rick-devops-01/mytest